spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ifindmytreasure/config-repo.git
          username: 17802532475@163.com
          password: zdwxfwby1230629
          basedir: /home
  rabbitmq:
    host: 47.101.189.10
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*" #actuator/routes查看所有路由
