eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: clientName
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: eurekaServer
#server:
#  port: 8761